name: Build
on: 
  push:
    branches:
      - 'master'

jobs:
  build:
    env:
      Configuration: Release
      SlnFile: .\Nustache.sln
    
    runs-on: windows-latest

    steps:
    - name: Git config
      run: |
        git config --global http.postBuffer 524288000

    - name: Checkout
      uses: actions/checkout@v2.3.1
      with:
        submodules: 'recursive'

    - name: Setup Nuget.exe
      uses: warrenbuckley/Setup-Nuget@v1

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.1
  
    - name: Setup GitHub NuGet Registry (GPR)
      run: nuget sources Add -Name "GPR" -Source "https://nuget.pkg.github.com/genexuslabs/index.json" -UserName %GITHUB_ACTOR% -Password ${{ secrets.GITHUB_TOKEN }} 

    - name: Build
      run: |
        msbuild $Env:SlnFile /m /verbosity:minimal /p:GeneratePackageOnBuild=false

    - name: Pack
      run: |
        nuget pack .\Nustache.Core\Nustache.Core.csproj --no-restore --no-build --configuration $Env:Configuration /p:Platform=AnyCPU

    - name: Test
      run: |
        nunit-console ".\Nustache.Compilation.Tests\bin\Release\Nustache.Compilation.Tests.dll" ".\Nustache.Core.Tests\bin\Release\Nustache.Core.Tests.dll"

    - name: Publish packages
      run: |      
        Get-ChildItem .\dotnet\*.nupkg -Recurse |
          ForEach-Object {
            dotnet nuget push $_.FullName --source GPR
        }
